# Generated by Django 5.1.4 on 2025-01-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cost',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='sell',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
