# Generated by Django 5.1.4 on 2025-01-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_ventas', '0003_alter_products_cost_alter_products_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
