# Generated by Django 5.1.4 on 2025-01-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_ventas', '0005_products_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
