# Generated by Django 5.1.4 on 2025-01-26 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_ventas', '0006_alter_products_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(default=1)),
                ('total_import', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_ventas.products')),
            ],
        ),
    ]
