# Generated by Django 5.1.4 on 2025-01-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_ventas', '0007_sells'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totalimports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
            ],
        ),
    ]
